---

- name: rhsso | Create management user (clustered domain managment)
  shell: "{{ rhsso_home_path }}/bin/add-user.sh -ds {{ rhsso_management_user.name }} {{ rhsso_management_user.password }} | grep -o '<.*>'"
  register: secret_value

- name: rhsso | Copy rhsso config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.permissions }}"
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
  with_items:
    - { src: "rhsso.service.j2",
        dest: "/lib/systemd/system/rhsso.service",
        permissions: "0640" }
    - { src: "domain.xml.j2",
        dest: "{{ rhsso_home_path }}/domain/configuration/domain.xml",
        permissions: "0640" }
    - { src: "host-master.xml.j2",
        dest: "{{ rhsso_home_path }}/domain/configuration/host-master.xml",
        permissions: "0640" }
    - { src: "host-slave.xml.j2",
        dest: "{{ rhsso_home_path }}/domain/configuration/host-slave.xml",
        permissions: "0640" }
    - { src: "jdbc.module.xml.j2",
        dest: "{{ rhsso_jdbc_conf_path }}/module.xml",
        permissions: "0640" }
    - { src: "launch.sh",
        dest: "{{ rhsso_home_path }}/bin/launch.sh",
        permissions: "0750" }
  notify: restart rhsso

- name: rhsso | Copy Daemon script
  template:
    src: rhsso.service.j2
    dest: /lib/systemd/system/rhsso.service
    mode: 0644
  notify: restart rhsso

- name: rhsso | Firewall rule
  firewalld:
    port: 9999/tcp
    immediate: yes
    permanent: yes
    state: enabled
  when: "rhsso_firewalld == true"

- name: rhsso | Firewall rule
  firewalld:
    port: 8593/tcp
    immediate: yes
    permanent: yes
    state: enabled
  when: "rhsso_firewalld == true"

- name: rhsso | edit /etc/sysctl.conf to increase JGroup Rx buffer limits to 25MB UDP
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.core.rmem_max'
    line: net.core.rmem_max=26214400

- name: rhsso | edit /etc/sysctl.conf to increase JGroup Tx buffer limits to 1MB UDP
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.core.wmem_max'
    line: net.core.wmem_max=1048576

- name: rhsso | Manage service
  systemd:
    name: rhsso
    state: started
    enabled: True
    daemon_reload: yes