---
- name: rhsso | mkdir
  file:
    path: "{{ rhsso_install_path }}"
    state: directory

- name: rhsso | Download rhsso zip
  get_url:
    url: "{{ rhsso_url }}"
    dest: "/tmp/{{ rhsso_zip }}"

- name: rhsso | Extract zip in the install directory
  unarchive:
    copy: no
    src: "/tmp/{{ rhsso_zip }}"
    dest: "{{ rhsso_install_path }}"
    owner: "root"
    group: "root"

- name: rhsso | Create JDBC config paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
    recurse: yes
  with_items:
    - "{{ rhsso_jdbc_conf_path }}"

- name: rhsso | Create log paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
    recurse: yes
  with_items:
    - "{{ rhsso_log_path }}"

- name: rhsso | Download JDBC driver
  get_url:
    url: "{{ jdbc_url }}"
    dest: "{{ rhsso_jdbc_conf_path }}"
