---

- name: Java | install java-1.8.0-openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: unzip | install unzip
  yum:
    name: unzip
    state: present

- name: rhsso | mkdir
  file:
    path: "{{ rhsso_install_path }}"
    state: directory

- name: rhsso | Download rhsso zip
  get_url:
    url: "{{ rhsso_url }}"
    dest: "/tmp/"
  when: rhsso_source == 'url'

- name: rhsso| copy zip from bastion to rh-sso
  copy:
    src: "{{ rhsso_file }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
  when: rhsso_source == 'file'

- name: rhsso | Ensure rhsso group exists
  group:
    name: "{{ rhsso_group }}"
    state: present

- name: rhsso | Ensure rhsso user exists
  user:
    name: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
    shell: "{{ rhsso_user_shell }}"
    createhome: yes
    home: "{{ rhsso_user_home }}"
    uid: "{{ rhsso_user_uid }}"
    state: present

- name: rhsso | Extract zip in the install directory
  unarchive:
    copy: no
    src: "/tmp/{{ rhsso_zip }}"
    dest: "{{ rhsso_install_path }}"
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso | Create JDBC config paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
    recurse: yes
  with_items:
    - "{{ rhsso_jdbc_conf_path }}"

- name: rhsso | Create log paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
    recurse: yes
  with_items:
    - "{{ rhsso_log_path }}"

- name: rhsso | Download JDBC driver
  get_url:
    url: "{{ jdbc_url }}"
    dest: "{{ rhsso_jdbc_conf_path }}"
  when: rhsso_source == 'url'

- name: rhsso| copy jdbc from bastion to rh-sso
  copy:
    src: "{{ jdbc_file }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"
  when: rhsso_source == 'file'