---
- name: rhsso | mkdir
  file:
    path: "{{ rhsso_install_path }}"
    state: directory

- name: rhsso | Download rhsso zip
  get_url:
    url: "{{ rhsso_url }}"
    dest: "/tmp/{{ rhsso_zip }}"

- name: rhsso | Extract zip in the install directory
  unarchive:
    copy: no
    src: "/tmp/{{ rhsso_zip }}"
    dest: "{{ rhsso_install_path }}"
    owner: "root"
    group: "root"