---

- set_fact: uuid={{ 99999999 | random | to_uuid }}

- name: rhsso| copy CA bundle file to host
  copy:
    src: "{{ keystore.base_dir }}/{{ keystore.bundle }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso| copy cert file to host
  copy:
    src: "{{ keystore.base_dir }}/{{ keystore.certificate }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso| copy key file to host
  copy:
    src: "{{ keystore.base_dir }}/{{ keystore.private_key }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso | Add CA bundle to keystore
  shell: "keytool -import -keystore keycloak.jks.{{ uuid }} -file {{ keystore.bundle }} -alias root -noprompt -trustcacerts -storepass {{ keystore.keycloak_jks_password }}"
  args:
    chdir: /tmp/

- name: rhsso | Add certificate to keystore
  shell: "openssl pkcs12 -export -name {{ keystore.dns }} -in {{ keystore.certificate }} -inkey {{ keystore.private_key }} -out keystore.p12.{{ uuid }} -password pass:{{ keystore.keystore_p12_password }}"
  args:
    chdir: /tmp/

- name: rhsso | Complete keystore keycloak.jks creation
  shell: "keytool -importkeystore -destkeystore keycloak.jks.{{ uuid }} -srckeystore keystore.p12.{{ uuid }} -srcstoretype pkcs12 -alias {{ keystore.dns }} -deststorepass {{ keystore.keycloak_jks_password }} -srcstorepass {{ keystore.keystore_p12_password }}"
  args:
    chdir: /tmp/

- name: rhsso| copy key file to config directory
  copy:
    remote_src: True
    src: "/tmp/keycloak.jks.{{ uuid }}"
    dest: "/opt/rh/rh-sso-7.3/domain/configuration/keycloak.jks"
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso | Configure rhsso  to use the Keystore.jks file
  shell: "/opt/rh/rh-sso-7.3/bin/jboss-cli.sh -c '/host={{ hostvars[item]['hostName'] }}/core-service=management/security-realm=UndertowRealm:add()' "
  args:
    chdir: /opt/rh/rh-sso-7.3/bin/
  when: inventory_hostname in groups['rhsso-master']
  register: result
  with_items: "{{ groups.rhsso }}"

- name: rhsso | Configure rhsso  to use the Keystore.jks file
  shell: "/opt/rh/rh-sso-7.3/bin/jboss-cli.sh -c '/host={{ hostvars[item]['hostName'] }}/core-service=management/security-realm=UndertowRealm/server-identity=ssl:add(keystore-path=keycloak.jks, keystore-relative-to=jboss.domain.config.dir, keystore-password={{ keystore.keycloak_jks_password }})' "
  args:
      chdir: /opt/rh/rh-sso-7.3/bin/
  when: inventory_hostname in groups['rhsso-master']
  register: result
  with_items: "{{ groups.rhsso }}"

- name: rhsso | Configure rhsso  to use the Keystore.jks file
  shell: "/opt/rh/rh-sso-7.3/bin/jboss-cli.sh -c '/profile=auth-server-clustered/subsystem=undertow/server=default-server/https-listener=https:write-attribute(name=security-realm, value=UndertowRealm)' "
  args:
    chdir: /opt/rh/rh-sso-7.3/bin/
  when: inventory_hostname in groups['rhsso-master']
  register: result
  with_items: "{{ groups.rhsso-master }}"
