---

- name: rhsso| copy CA bundle file to host
  copy:
    src: "{{ keystore.bundle }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso| copy cert file to host
  copy:
    src: "{{ keystore.certificate }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso| copy key file to host
  copy:
    src: "{{ keystore.private_key }}"
    dest: /tmp/
    mode: 0644
    owner: "{{ rhsso_user }}"
    group: "{{ rhsso_group }}"

- name: rhsso | Add CA bundle to keystore
  shell: "keytool -import -keystore keycloak.jks -file {{ keystore.bundle }} -alias root"
  args:
    chdir: /tmp/

- name: rhsso | Add certificate to keystore
  shell: "openssl pkcs12 -export -name {{ keystore.dns }} -in {{ keystore.certificate }} -inkey {{ keystore.private_key }} -out keystore.p12"
  args:
    chdir: /tmp/

- name: rhsso | Complete keystore keycloak.jks creation
  shell: "keytool -importkeystore -destkeystore keycloak.jks -srckeystore keystore.p12 -srcstoretype pkcs12 -alias {{ keystore.dns }}"
  args:
    chdir: /tmp/




