---

- name: rhsso | Install
  include: install.yml
  tags:
    - install

- name: rhsso | Configure
  include: config.yml
  tags:
    - configure

- name: rhsso | Users
  include: users.yml
  when: inventory_hostname in groups['rhsso-master']
  tags:
    - users

- name: rhsso | Keystore
  include: keyStore.yml
  tags:
    - keystore