---

- name: rhsso | Install
  include: install.yml
  tags:
    - install
- name: rhsso | Users
  include: users.yml
  tags:
    - users
- name: rhsso | Configure
  include: config.yml
  tags:
    - configure